# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
workspace 'WAIE.xcworkspace'
project 'WAIE.xcodeproj'

target 'WAIE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WAIE

end
